-- phpMyAdmin SQL Dump
-- version 5.1.2
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1:3306
-- Généré le : lun. 02 mai 2022 à 07:48
-- Version du serveur : 5.7.36
-- Version de PHP : 8.1.0

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `autocompletion`
--

-- --------------------------------------------------------

--
-- Structure de la table `country`
--

DROP TABLE IF EXISTS `country`;
CREATE TABLE IF NOT EXISTS `country` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `capitalCity` varchar(255) NOT NULL,
  `continent` varchar(255) NOT NULL,
  `flagImage` varchar(255) NOT NULL,
  `countryMapImage` varchar(255) NOT NULL,
  `description` longtext NOT NULL,
  `population` varchar(255) NOT NULL,
  `area` varchar(255) NOT NULL,
  `currency` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=26 DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `country`
--

INSERT INTO `country` (`id`, `name`, `capitalCity`, `continent`, `flagImage`, `countryMapImage`, `description`, `population`, `area`, `currency`) VALUES
(1, 'France', 'Paris', 'Europe', 'france1.png', 'france2.png', 'La France, pays de l\'Europe occidentale, compte des villes médiévales, des villages alpins et des plages. Paris, sa capitale, est célèbre pour ses maisons de mode, ses musées d\'art classique, dont celui du Louvre, et ses monuments comme la Tour Eiffel. Le pays est également réputé pour ses vins et sa cuisine raffinée. Les peintures rupestres des grottes de Lascaux, le théâtre romain de Lyon et l\'immense château de Versailles témoignent de sa riche histoire. ', '67,39 millions (2020)', '543 940 km²', 'Euro'),
(2, 'Espagne', 'Madrid', 'Europe', 'espagne1.png', 'espagne2.png', 'L\'Espagne est un pays européen situé sur la péninsule ibérique et comprenant 17 régions autonomes à la géographie et aux cultures diverses. Madrid, la capitale, abrite le palais royal et le musée du Prado, où sont exposées les œuvres d\'artistes européens. On peut admirer à Ségovie un château médiéval (l\'Alcazar) et un aqueduc romain intact. La capitale de la Catalogne, Barcelone, se caractérise par les monuments modernistes d\'Antoni Gaudí, notamment la Sagrada Família.', '47,35 millions (2020)', '505 990 km²', 'Euro'),
(3, 'Italie', ' Rome', 'Europe', 'italie1.png', 'italie2.png', 'L\'Italie, pays européen bordé par la Méditerranée et l\'Adriatique, a laissé une forte empreinte sur la culture et la cuisine occidentales. Sa capitale, Rome, abrite le Vatican ainsi que des trésors artistiques et des ruines antiques. Les autres grandes villes comprennent Florence, avec des chefs-d\'œuvre de la Renaissance comme le David de Michel-Ange et le dôme de Brunelleschi, Venise, la ville des canaux, et Milan, la capitale italienne de la mode', ' 59,55 millions (2020)', '302 073 km²', 'Euro'),
(4, 'Allemagne', 'Berlin', 'Europe', 'allemagne1.png', 'allemagne2.png', 'L\'Allemagne est un pays d\'Europe de l\'Ouest dont le paysage se compose de forêts, de rivières, de chaînes montagneuses et de plages sur la mer du Nord. Son histoire remonte à plus de 2 000 ans en arrière. Dotée d\'une vie artistique et nocturne animée, Berlin, sa capitale, inclut la porte de Brandebourg et de nombreux sites en lien avec la Seconde Guerre mondiale. Munich est connue pour son Oktoberfest et ses bars à bières, notamment l\'Hofbräuhaus qui date du XVIe siècle. Francfort, avec ses gratte-ciel, abrite la Banque centrale européenne', '83,24 millions (2020)', '357 588 km²', 'Euro'),
(5, 'Portugal', 'Lisbonne', 'Europe', 'portugal1.png', 'portugal2.png', 'Le Portugal est un pays du sud de l\'Europe, sur la péninsule Ibérique, délimité en partie par l\'Espagne. Sa situation au bord de l\'océan Atlantique a influencé de nombreux aspects de sa culture : la morue salée et les sardines grillées sont des plats nationaux, les plages de l\'Algarve sont très prisées et une grande partie de l\'architecture du pays date des années 1500 aux années 1800, période pendant laquelle le Portugal était un empire maritime puissant.', '10,31 millions (2020)', '92 212 km²', 'Europe'),
(6, 'Angleterre', 'Londres', 'Europe', 'angleterre1.png', 'angleterre2.png', 'L\'Angleterre, berceau de Shakespeare et des Beatles, est un pays des îles britanniques, à la frontière avec l\'Écosse et le Pays de Galles. Londres, sa capitale située sur la Tamise, abrite le Parlement, Big Ben et la tour de Londres, qui date du XIe siècle. Il s\'agit également d\'un pôle multiculturel moderne pour les arts et le commerce. Les autres grandes villes du pays sont Manchester, Birmingham, Liverpool, Bristol, et les centres universitaires d\'Oxford et de Cambridge.', '55,98 millions (2018)', '242 495 km²', 'Livre sterling'),
(7, 'Guinée', 'Conakry', 'Afrique', 'guinee1.png', 'guinee2.png', 'La Guinée est un pays d\'Afrique de l\'Ouest bordé par l\'océan Atlantique à l\'ouest. Elle est réputée pour la réserve naturelle intégrale du Mont Nimba, située au sud-est du pays. La réserve protège une chaîne de montagnes boisée abritant des plantes et des animaux de la région, dont des chimpanzés et des crapauds vivipares. Sur la côte, la capitale, Conakry, accueille la grande mosquée, moderne, et le musée national, qui contient des objets régionaux.', '13,13 millions (2020) ', '245 857 km²', 'Franc guinéen'),
(8, 'Sénégal', 'Dakar', 'Afrique', 'senegal1.png', 'senegal2.png', 'Le Sénégal est un pays situé sur la côte ouest de l\'Afrique et doté d\'un héritage colonial français et de nombreuses attractions naturelles. Dakar, la capitale, comprend le quartier historique de la Médina et le célèbre musée Théodore Monod, exposant des œuvres d\'art africain. Elle est également réputée pour sa vie nocturne, centrée sur la musique mbalax, originaire du Sénégal. Saint-Louis, ancienne capitale de l\'Afrique-Occidentale française, abrite une vieille ville à l\'architecture coloniale', '16,74 millions (2020)', '196 722 km²', ' Franc CFA'),
(9, 'Égypte', 'Le Caire', 'Afrique', 'egypte1.png', 'egypte2.png', 'L\'Égypte est un pont entre l\'Afrique du Nord-Est et le Moyen-Orient et son histoire remonte à l\'époque des pharaons. Des monuments millénaires bordent les berges de la fertile vallée du Nil, notamment le sphinx et les pyramides colossales de Gizeh. La ville de Louxor abrite le temple de Karnak et ses hiéroglyphes, ainsi que les tombeaux de la vallée des rois. Le Caire, la capitale, regorge de sites ottomans, comme la mosquée Mohammed Ali ou le musée égyptien et ses trésors d\'antiquités. ', '102,3 millions (2020)', '1,002 million km²', ' Livre égyptienne'),
(10, 'Maroc', 'Rabat', 'Afrique', 'maroc1.png', 'maroc2.png', 'Le Maroc, pays d\'Afrique du Nord sur le littoral de l\'Atlantique et de la Méditerranée, se distingue par ses influences berbères, arabes et européennes. La médina de Marrakech, quartier médiéval aux allures de labyrinthe, est un lieu animé, avec sa place Jemaa el-Fna et ses souks (marchés) vendant des céramiques, des bijoux et des lanternes en métal. La casbah des Oudayas à Rabat, la capitale, est un fort royal du XIIe siècle qui surplombe l\'océan.', ' 36,91 millions (2020)', '710 850 km²', 'Dirham marocain'),
(11, 'Algérie', 'Alger', 'Afrique', 'algerie1.png', 'algerie2.png', 'L\'Algérie est un pays nord-africain doté d\'un littoral sur la mer Méditerranée et d\'un intérieur désertique, le Sahara. De nombreux empires y ont laissé leur marque, comme les anciennes ruines romaines de Tipasa, en bord de mer. Dans la capitale, Alger, des sites ottomans, tels que la mosquée Ketchaoua, datant de 1612 environ, bordent le quartier de la Casbah. Perché sur une colline, cet endroit dispose d\'allées étroites et d\'escaliers. La basilique Notre-Dame d\'Afrique, arborant une architecture néo-byzantine, date de la domination coloniale française.', ' 43,85 millions (2020)', '2,382 millions km²', 'Dinar algérien'),
(12, 'Afrique du Sud', 'Le Cap, Pretoria, Bloemfontein', 'Afrique', 'afs1.png', 'afs2.png', 'L\'Afrique du Sud est un pays situé à l\'extrémité australe du continent africain et composé de différents écosystèmes. À l\'intérieur des terres, le parc national Kruger abrite du gros gibier et propose des safaris. Le Cap occidental offre des plages, des vignobles luxuriants autour de Stellenbosch et Paarl, des falaises rocheuses au cap de Bonne-Espérance, des forêts et des lagons le long de la Garden Route, ainsi que la ville du Cap, située au pied de la montagne de la Table au sommet plat.', ' 59,31 millions (2020)', '1,221 million km²', 'Rand'),
(13, 'Japon', 'Tokyo', 'Asie', 'japon1.png', 'japon2.png', 'Le Japon est un pays insulaire situé dans l\'océan Pacifique. Il comporte des villes denses, des palais impériaux, des parcs nationaux montagneux ainsi que des milliers de temples et de sanctuaires. Les trains à grande vitesse Shinkansen relient les îles principales de Kyūshū (avec les plages subtropicales d\'Okinawa), Honshū (où se trouvent Tokyo et le mémorial en hommage aux victimes du bombardement atomique d\'Hiroshima) et Hokkaidō (prisée pour le ski). Tokyo, la capitale, est réputée pour ses gratte-ciel, ses magasins et sa culture populaire.', '125,8 millions (2020)', ' 377 975 km²', 'Yen'),
(14, 'Chine', 'Pékin', 'Asie', 'chine1.png', 'chine2.png', 'La Chine est un pays très peuplé d’Asie de l’est. Son territoire immense présente des paysages variés : prairies, déserts, montagnes, lacs, rivières et plus de 14 000 km de littoral. Pékin, la capitale à l’architecture moderne, conserve également des sites historiques, comme le palais de la Cité interdite et la place Tian Anmen. Shanghaï est l\'un des plus grands centres financiers mondiaux et comporte de nombreux gratte-ciels. L’emblématique Grande Muraille de Chine partage le nord du pays d’est en ouest.', ' 1,402 milliard (2020)', '9,597 millions km²', ' Yuan'),
(15, 'Inde', 'New Delhi', 'Asie', 'inde1.png', 'inde2.png', 'Immense pays du sud de l\'Asie, l\'Inde offre un paysage varié, des pics de l\'Himalaya au littoral de l\'océan Indien. Son histoire remonte à 5 millénaires. Au nord se trouvent des sites datant de l\'empire moghol tels que le Fort rouge et l\'imposante mosquée Jama Masjid, à Delhi, ainsi que l\'emblématique mausolée du Tāj Mahal, à Agra. Les pèlerins viennent faire leurs ablutions dans les eaux du Gange, à Bénarès. Rishikesh est la capitale du yoga, mais aussi le point de départ des randonnées vers l\'Himalaya.', '1,38 milliard (2020) ', '3,287 millions km²', 'Roupie indienne'),
(16, 'Corée du Sud', 'Séoul', 'Asie', 'cs1.png', 'cs2.png', 'La Corée du Sud, un pays d\'Asie de l\'Est, occupe la moitié sud de la péninsule de Corée. Elle partage l\'une des frontières les plus fortement militarisées du monde avec la Corée du Nord. Elle est également connue pour sa campagne vallonnée et verdoyante parsemée de cerisiers et de temples bouddhistes datant de plusieurs siècles, ainsi que pour les villages de pêcheurs de sa côte, ses îles subtropicales et ses villes high-tech comme Séoul, sa capitale.', '51,78 millions (2020)', '100 210 km²', ' Won sud-coréen'),
(18, 'Thaïlande', 'Asie', 'Asie', 'thailande1.png', 'thailande2.png', 'La Thaïlande est un pays d\'Asie du Sud-Est. Elle est réputée pour ses plages tropicales, ses palais royaux opulents, ses ruines anciennes et ses temples ornés présentant des statues de Bouddha. À Bangkok, la capitale, un paysage urbain ultramoderne côtoie des communautés tranquilles au bord des canaux et les emblématiques temples de Wat Arun, Wat Pho et Wat Phra Kaeo (temple du Bouddha d\'émeraude). Les stations balnéaires situées à proximité comprennent la dynamique Pattaya et la ville branchée de Hua Hin.', '69,8 millions (2020)', '513 120 km²', 'Baht'),
(19, 'États-Unis', 'Washington', 'Amérique', 'es1.png', 'es2.png', 'Les États-Unis sont un pays constitué de 50 états et couvrant une vaste portion de l\'Amérique du Nord, avec l\'Alaska au nord-ouest et Hawaï étendant la présence du pays dans l\'océan Pacifique. Les principales villes de la côte atlantique sont New York, centre international financier et culturel, et Washington, la capitale. Dans la région du Midwest, la métropole de Chicago est connue pour son architecture influente et sur la côte ouest, le quartier d\'Hollywood à Los Angeles est célèbre pour ses studios de cinéma.', '329,5 millions (2020)', '9,834 millions km²', 'Dollar américain'),
(20, 'Brésil', 'Brasília', 'Amérique', 'bresil1.png', 'bresil2.png', 'Le Brésil, vaste pays d\'Amérique du Sud, s\'étend du bassin amazonien au nord à des vignobles et aux chutes d\'Iguaçu au sud. La ville de Rio de Janeiro, caractérisée par sa statue du Christ Rédempteur de 38 mètres de haut située au sommet du Corcovado, est réputée pour ses plages très fréquentées de Copacabana et d\'Ipanema, ainsi que pour son énorme carnaval animé, avec défilés de chars, costumes flamboyants, et musique et danse samba.', ' 212,6 millions (2020)', ' 8,516 millions km²', 'Réal brésilien'),
(21, 'Canada', 'Ottawa', 'Amérique', 'canada1.png', 'canada2.png', 'Le Canada est un pays nord-américain situé entre les États-Unis au sud et le cercle polaire au nord. Les principales villes sont Toronto, Vancouver, centre du cinéma de la côte ouest, Montréal et Québec, toutes deux francophones, et Ottawa, la capitale. Le Canada compte, parmi ses vastes étendues sauvages, le parc national de Banff avec ses nombreux lacs situé dans les montagnes Rocheuses. Il abrite également les célèbres et majestueuses chutes du Niagara.', '38,01 millions (2020)', '9,985 millions km²', 'Dollar canadien'),
(22, 'Cuba', 'La Havane', 'Amérique', 'cuba1.png', 'cuba2.png', 'Cuba est un État insulaire communiste des Caraïbes. On y trouve des plages de sable spectaculaires et des champs de tabac pour la production des cigares légendaires. La capitale, La Havane, est riche de maisons aux façades pastel, de voitures des années 1950 et d\'une architecture hispano-coloniale du XVIe siècle dans la vieille Havane. On peut écouter de la salsa dans des clubs de danse et assister à des spectacles de cabaret au célèbre Tropicana.', '11,33 millions (2020)', '109 884 km²', 'Peso cubain'),
(23, 'Argentine', 'Buenos Aires', 'Amérique', 'argentine1.png', 'argentine2.png', 'L\'Argentine est un grand pays d\'Amérique du Sud au relief très varié où se côtoient les montagnes des Andes, les lacs glaciaires et la pampa, de grandes plaines de pâturage où paissent les célèbres bovins du pays. L\'Argentine est réputée pour le tango et la musique. Au centre de Buenos Aires, la grande capitale cosmopolite, se trouve la place de Mai, bordée de bâtiments datant du XIXe siècle tels que la Casa Rosada (Maison rose), le palais présidentiel à balcon. ', '45,38 millions (2020)', '2,78 millions km²', 'Peso argentin'),
(24, 'Mexique', 'Mexico', 'Amérique', 'mexique1.png', 'mexique2.png', 'Situé entre les États-Unis et l\'Amérique centrale, le Mexique est un pays réputé pour ses plages du Pacifique et du golfe du Mexique, ainsi que pour ses paysages variés - entre montagnes, déserts et jungles. Il est pourvu de ruines anciennes comme Teotihuacan et la cité maya de Chichén Itzá ainsi que de villes datant de l\'époque coloniale espagnole. Sa capitale Mexico propose un retour à la modernité avec ses boutiques haut de gamme, ses musées renommés et ses restaurants gastronomiques.', '128,9 millions (2020)', '1,973 million km²', 'Peso mexicain'),
(25, 'Australie', 'Canberra', 'Océanie', 'australie1.png', 'australie2.png', 'L\'Australie est un pays et continent entouré par les océans Indien et Pacifique. Ses principales villes, Sydney, Brisbane, Melbourne, Perth et Adélaïde, sont bâties sur la côte. La capitale, Canberra, est quant à elle située à l\'intérieur des terres. Le pays est connu pour l\'opéra de Sydney, la Grande Barrière de corail, ses grandes étendues sauvages et désertiques appelées l\'Outback, et ses espèces animales uniques comme le kangourou et l\'ornithorynque.', '25,69 millions (2020)', '7,692 millions km²', 'Dollar australien');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
